// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk1roZZObZPqgSZEXqLwSX55e9eAcniPY',
    appId: '1:174422530336:web:f6f4454930c29fc7a35f45',
    messagingSenderId: '174422530336',
    projectId: 'todolist-8d0b2',
    authDomain: 'todolist-8d0b2.firebaseapp.com',
    storageBucket: 'todolist-8d0b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9JFYhDuS4MVjRqUuxBC4ZiicKAEZ8Us',
    appId: '1:174422530336:android:b71f3d4bcc08a259a35f45',
    messagingSenderId: '174422530336',
    projectId: 'todolist-8d0b2',
    storageBucket: 'todolist-8d0b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsAf8CRmHG6DdJzgJGodtmZflxzYu14TU',
    appId: '1:174422530336:ios:308c99c9535c7dc2a35f45',
    messagingSenderId: '174422530336',
    projectId: 'todolist-8d0b2',
    storageBucket: 'todolist-8d0b2.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsAf8CRmHG6DdJzgJGodtmZflxzYu14TU',
    appId: '1:174422530336:ios:848f205178f8f199a35f45',
    messagingSenderId: '174422530336',
    projectId: 'todolist-8d0b2',
    storageBucket: 'todolist-8d0b2.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
